name: Java application 

on:
  work_dispatch:
  push: 
    branches:
      - main
  pull request:
    branches: 
      - main           


jobs:
  build:

    runs-on: Ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "skandasbhat" --password-stdin
        docker image build -t skandasbhat/hello-java:latest .
        docker push skandasbhat/hello-java:latest
        
    - name: run Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "skandasbhat" --password-stdin
        docker pull skandasbhat/hello-java:latest
        docker run skandasbhat/hello-java:latest
