name: Java application 

on:
work_dispatch:
  push: 
    branches: [master .]
  pull request:
    branches: [master .]             

  jobs:
  build:

    runs-on: Ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "skandasbhat" --password-stdin
        docker image build -t skandasbhat/hello-java .
        docker push skandasbhat/hello-java
